version: '3.9'

services:
  web:
    image: 389798/pin-image
    container_name: pin-container
    depends_on:
      - db
    env_file:
      - .development.env
    restart: always
    ports:
      - 3501:3500
    volumes:
      - ./src/auth
      - ./src/search
      - ./src/comments
      - ./src/jwt-token
      - ./src/messages
      - ./src/boards
      - ./src/chat
      - ./src/pins
      - ./src/roles
      - ./src/users
      - ./src/notification
      - ./src/notes
      - ./src/user-settings
      - ./src/history
    networks:
      - pinterest-network

  db:
    image: postgres:13
    container_name: postgres-pin-container
    ports:
      - 5432:5432
    env_file:
      - .development.env
    depends_on:
      - redis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pinterest
      - POSTGRES_PASSWORD=rambler557
    networks:
      - pinterest-network

  redis:
    image: redis
    container_name: redis-pin-container
    ports:
      - 6379:6379
    command: ['redis-server', '--port', '6379']
    volumes:
      - redis_data:/usr/local/etc/redis
    networks:
      - pinterest-network

  nginx:
    image: 389798/nginx-loadbalancer
    container_name: loadbalance-pin-container
    ports:
      - 3500:80
    depends_on:
      - web
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pinterest-network

volumes:
  postgres_data:
  redis_data:
  nginx.conf:

networks:
  pinterest-network:
    driver: bridge
