import { Entity, PrimaryGeneratedColumn, Column, OneToOne } from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';
import UserEntity from './users.entity';

@Entity({ name: 'tokens' })
export default class JwtTokenEntity {
  @ApiProperty({
    type: Number,
    example: 2,
    description: 'Autogenerated primary key of the  table',
  })
  @PrimaryGeneratedColumn()
  public id: number;

  @ApiProperty({
    type: String,
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',
    description: 'Reference on the refresh token',
  })
  @Column({ type: 'varchar', nullable: false })
  public token: string;

  @OneToOne(() => UserEntity, (user) => user)
  public user: UserEntity;
}
