import { Entity, Column, PrimaryGeneratedColumn, ManyToOne } from 'typeorm';
import { Field, ObjectType } from '@nestjs/graphql';
import { ApiProperty } from '@nestjs/swagger';
import { BoardEntity } from './board.entity';
import { status } from '../dto/create-notes.dto';

@Entity({ name: 'notes' })
@ObjectType('notes')
export default class NotesEntity {
  @ApiProperty({ example: 2, description: 'Autogenerated primary key' })
  @PrimaryGeneratedColumn()
  public id: number;

  @ApiProperty({
    example: 'Add new pin into current board',
    description: 'Title of the Note',
  })
  @Column({ type: 'varchar' })
  public title: string;

  @ApiProperty({
    example:
      "I had liked 2 some cool pins: 1) Uncharted 4 A thief's end and 2) Young Nathan Drake",
    description: '',
  })
  @Column({ type: 'varchar' })
  public text: string;

  @ApiProperty({
    example: 'In progress',
    description: 'Status of the note activity',
  })
  @Column({ type: 'varchar' })
  public status: status;

  // @ApiProperty({
  //   type: () => BoardEntity,
  //   example: 'Best game ever',
  //   description: 'Current board for current note',
  // })
  // @Field((type) => BoardEntity)
  // @ManyToOne(() => BoardEntity, (board) => board.notes)
  // public board: BoardEntity;
}
