import { ApiProperty } from '@nestjs/swagger';
import {
  Entity,
  OneToOne,
  PrimaryGeneratedColumn,
  OneToMany,
  JoinColumn,
} from 'typeorm';
import UserEntity from './users.entity';
import PinEntity from './pin.entity';

@Entity({ name: 'timeline_settings' })
export default class TimeLineEntity {
  @ApiProperty({
    type: Number,
    example: 1,
    description: 'Autogenerated primary key of that column',
  })
  @PrimaryGeneratedColumn()
  public id: number;

  // @ApiProperty({
  //   type: () => AccountSettingsEntity,
  //   example: '{ theme: , sounds: true }',
  //   description: 'Settings of the current user account',
  // })
  // @OneToOne(() => AccountSettingsEntity, (account) => account.timeline)
  // @JoinColumn()
  // public settings: AccountSettingsEntity;

  @ApiProperty({
    type: () => PinEntity,
    example: '[Norman Reedus boom, BB with some different things, TypeScript]',
    description: 'Pins, which user had seen',
  })
  @OneToMany(() => PinEntity, (pin) => pin)
  public history: PinEntity[];

  @ApiProperty({
    type: () => UserEntity,
    example: '[Lunaraxe63, MashaLover, Terpila63]',
    description: 'Accounts, which user subscribed',
  })
  @OneToMany(() => UserEntity, (user) => user)
  public profiles: UserEntity[];
}
